### PR TITLE
Omansh

### PR DESCRIPTION
**Pull request by Omanshb**
This PR contains part 1 and part 2 of the beginner project for Omansh Bainsla.

### CODE REVIEW

**Comment by karkir0003** [comment]
@Omanshb Can you please include detailed screen recording showing that the completion of Part 2 in the beginner project is giving the valid result?

**Review by karkir0003 — CHANGES_REQUESTED** [review]
Please include detailed screen recording

**Comment by Omanshb** [comment]
https://drive.google.com/file/d/1S4Qgzw9cP1T8yIaUem8Zo25yiuTdbZIp/view?usp=sharing

Here is a screen recording of all my part2 changes

**Comment by karkir0003** [comment]
@Omanshb looks good to me. I'll close this PR since we don't want to merge this work into the actual DLP app

**Pull request closed without merging**
