### PR TITLE
hartej (part 2)

### PR DESCRIPTION
**Pull request by hartejsingh12**
# hartej (part 2)

Github Issue Number Here: <YOUR_GITHUB_ISSUE_NUMBER_HERE (include the hashtag)>
**What user problem are we solving?**

**What solution does this PR provide?**

**Testing Methodology**
How did you test your changes and verify that existing 
functionality is not broken

**Any other considerations**

Screen recording:
https://www.youtube.com/watch?v=vcNmMt4-spQ

### CODE REVIEW

**Comment by karkir0003** [comment]
Hey @hartejsingh12, there is an issue in the build check where you have two different, yet similar if conditions that lead to the same outcome. We should clean that up in order to get into the clean code habit

**Comment by hartejsingh12** [comment]
> Hey @hartejsingh12, there is an issue in the build check where you have two different, yet similar if conditions that lead to the same outcome. We should clean that up in order to get into the clean code habit

**Comment by hartejsingh12** [comment]
> Hey @hartejsingh12, there is an issue in the build check where you have two different, yet similar if conditions that lead to the same outcome. We should clean that up in order to get into the clean code habit

Fixed!

**Comment by karkir0003** [comment]
@hartejsingh12 Good work on this. I'll be marking your PR as closed since we don't want to actually merge these changes into the real DLP app. Looking forward to your Part 3 PR

**Pull request closed without merging**
